# Generated by Django 2.0.7 on 2020-12-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
    ]
