# Generated by Django 2.0.7 on 2020-12-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default=-1.0),
            preserve_default=False,
        ),
    ]
