# Generated by Django 2.0.7 on 2020-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='promo',
            field=models.CharField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
    ]
